### ISSUE TITLE
Run styx failed

### ISSUE THREAD

**Issue by Vancir** [mariusschulz/styx-cli#1]
Runing `styx` after the command `npm install -g styx-cli`, there shows error:

```
module.js:540
    throw err;
    ^

Error: Cannot find module '../util/ArrayUtil'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vancir/Documents/software/node/lib/node_modules/styx-cli/node_modules/styx/lib/exporters/dot.js:2:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by mariusschulz** [comment]
@Vancir I just updated both `styx-cli` and `styx` on npm. Please try again! This should now work.
